### ISSUE TITLE
Draft Monthly Checklist - Actuals

### ISSUE THREAD

**Issue by mary-curd** [mary-curd/support-wfm#2]
### Enterprise

- [ ] Seat Counts
- [ ] Total Tickets
- [ ] Total Public Comments
- [ ] Headcounts
- [ ] Calculate IPX
- [ ] Calculate Touches per Case
- [ ] Calculate Time per Touch

### Developer - Accounts

- [ ] Seat Counts
- [ ] Total Tickets
- [ ] Total Public Comments
- [ ] Headcounts
- [ ] Calculate IPX
- [ ] Calculate Touches per Case
- [ ] Calculate Time per Touch

### Developer - Technical

- [ ] Seat Counts
- [ ] Total Tickets
- [ ] Total Public Comments
- [ ] Headcounts
- [ ] Calculate IPX
- [ ] Calculate Touches per Case
- [ ] Calculate Time per Touch

### Premium

- [ ] Seat Counts
- [ ] Total Tickets
- [ ] Total Public Comments
- [ ] Headcounts
- [ ] Calculate IPX
- [ ] Calculate Touches per Case
- [ ] Calculate Time per Touch

### Community

- [ ] Seat Counts
- [ ] Total New Threads
- [ ] Total New Comments
- [ ] Headcounts
- [ ] Calculate IPX
- [ ] Calculate Time per Thread
